@baseUrl = http://localhost:3001
@apiToken = 456

################
#### Events ####
################

### Create Event
# @name createEvent
POST {{baseUrl}}/events
Content-Type: application/json
X-Api-Token: {{apiToken}}

{
  "name": "Event 1",
  "description": "First event",
  "date": "2024-06-17T00:00:00", 
  "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

### Get All Events
GET  {{baseUrl}}/events
X-Api-Token: {{apiToken}}


### Get Event
GET {{baseUrl}}/events/{{eventId}}
X-Api-Token: {{apiToken}}

### Update Event
PATCH {{baseUrl}}/events/{{eventId}}
Content-Type: application/json
X-Api-Token: {{apiToken}}

{
  "name": "Event 1",
  "description": "First event - updated",
  "date": "2024-06-17T00:00:00", 
  "price": 100
}

### Delete Event
DELETE {{baseUrl}}/events/{{eventId}}
X-Api-Token: {{apiToken}}

###############
#### Spots ####
###############

### Create Spot
# @name createSpot
POST {{baseUrl}}/events/{{eventId}}/spots
Content-Type: application/json
X-Api-Token: {{apiToken}}

{
  "name": "A1"
}

###
@spotId = {{ createSpot.response.body.id }}
@spotName = {{ createSpot.response.body.name }}

### Get All Spots
GET {{baseUrl}}/events/{{eventId}}/spots
X-Api-Token: {{apiToken}}

### Get Spot
GET {{baseUrl}}/events/{{eventId}}/spots/{{spotId}}
X-Api-Token: {{apiToken}}

### Update Spot
PATCH {{baseUrl}}/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json
X-Api-Token: {{apiToken}}

{
  "name": "A2"
}

### Delete Spot
DELETE {{baseUrl}}/events/{{eventId}}/spots/{{spotId}}
X-Api-Token: {{apiToken}}

### Reserve Spot
POST {{baseUrl}}/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: {{apiToken}}

{
  "spots": ["{{spotName}}"],
  "ticketType": "full",
  "email": "test@test.com"
}
