services:
  nextjs-web-app:
    build: .
    ports:
      - 3002:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: sh .docker/app/entrypoint.sh
