@baseUrl = http://localhost:8080

################
#### Events ####
################

### Create Event
# @name createEvent
POST {{baseUrl}}/events
Content-Type: application/json

{
  "name": "Tech Conference 2025",
  "location": "Convention Center",
  "organization": "Tech Innovators Inc.",
  "rating": "L14",
  "date": "2024-09-15T09:00:00Z",
  "capacity": 500,
  "price": 150.0,
  "partner_id": 2,
  "image_url": "http://example.com/image.jpg",
  "spots": ["B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10"]
}

###
@eventId = {{ createEvent.response.body.id }}

### Get All Events
GET {{baseUrl}}/events

### Get Event
GET {{baseUrl}}/events/{{eventId}}

### Get Event Spots
GET {{baseUrl}}/events/{{eventId}}/spots

### Buy Tickets
POST {{baseUrl}}/checkout
Content-Type: application/json

{
  "event_id": "{{eventId}}",
  "spots": ["B1"],
  "ticket_type": "full",
  "card_hash": "example_card_hash",
  "email": "user@example.com"
}
