# Add this line in your /etc/hosts file:
# 127.0.0.1 host.docker.internal

services:
  go-ticket-sales-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      go-ticket-sales-api-mysql:
        condition: service_healthy
    entrypoint: sh .docker/app/entrypoint.sh

  go-ticket-sales-api-mysql:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
